# Generated by Django 4.1.5 on 2023-04-30 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
